version: '3.1'
services:

  db:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./database_config/manager.sql:/docker-entrypoint-initdb.d/manager.sql:Z
